### ISSUE TITLE
Update zilliqa-js to `0.3.0`. 

### ISSUE THREAD

**Issue by jakeonchain** [zilliqalight/zilliqa-light-wallet#3]
This release will include utils methods for converting Zilliqa's unit accounting. Zil = 10^0, Li = 10^-6, Qa = 10^-12.

`gasPrice` will advised to be denominated in Li in the Users' display, but accounted as Qa when doing `createTransaction` method. Reason being we expect the `gasPrice` to be around 1,000 Li at the beginning.

Release status: https://github.com/Zilliqa/Zilliqa-JavaScript-Library/releases

**Comment by evesnow91** [comment]
Upon some discussion internally, we think we should display the following for wallet users:
- Account balance in terms of  **Zil**, up to 6 decimal placing (e.g `10.000000` Zil)
- `gasPrice` in terms of **Li** at the sending screen. (e.g default `1,000` Li)
- Add an info pop out at the `gasPrice` tab to describe "Note: 1 Zil = 1,000,000 Li".

**Comment by jakeonchain** [comment]
@evesnow91 thanks, we will wok on those changes.

**Comment by jakeonchain** [comment]
@evesnow91 I have upgraded the wallet to use `0.3.4`.

Now we use `Qa` as the unit for the `createTransaction` method. Display up to 6 decimal for the Zil balance. And add a description to the Send token screen for the Li and Zil conversion rate.

Also, we fix some issue for the wallet to adopt the changes in zilliqa-js `0.3.4`. The wallet has been uploaded to Chrome store https://chrome.google.com/webstore/detail/pcaeihaibgpndmlpnchfnlhbgmlifmoj/ please have a look, thanks.

I close this issue for now, feel free to re-open the issue if you have any questions.
