### ISSUE TITLE
Mainnet support

### ISSUE THREAD

**Issue by jakeonchain** [zilliqalight/zilliqa-light-wallet#5]
When mainnet launches on 31st January 2019, we will need you to add a new endpoint for the mainnet. (e.g. https://mainnet-api.zilliqa.com)

Mainnet api URL will remain as https://api.zilliqa.com. Testnet api URL will be TBD.
Change CHAIN_ID = 1 for Mainnet. Change CHAIN_ID = 2 for Testnet

**Comment by evesnow91** [comment]
Testnet `CHAIN_ID` will be `333` instead.
Mainnet `CHAIN_ID` will still be `1`.

**Comment by jakeonchain** [comment]
Fixed by 11999af9bfabf929efc7de1193d8ad111b2dfe8f
