### ISSUE TITLE
Cant execute transfers - bad private key

### ISSUE THREAD

**Issue by Endijs** [zilliqalight/zilliqa-light-wallet#6]
I tried to execute transfer, however i receive an error " Send failed, Error: Bad private key., please retry later." . I have tried to reinstall extension from web store, tried even to rebuild from source and load it. After recovering account from mnemonic phrase i see my balance. However when i try to execute transfer " Send failed, Error: Bad private key., please retry later."  error is shown. As I cant export private key, cant do anything with the funds.

**Comment by jakeonchain** [comment]
@Endijs thanks for reporting that, Zilliqa has update the API, and I am working on it. I will let you know once we release a new version.

**Comment by jakeonchain** [comment]
@Endijs Wallet has updated and push to Chrome store https://chrome.google.com/webstore/detail/pcaeihaibgpndmlpnchfnlhbgmlifmoj/ .

I close this issue for now and please feel free to re-open it if you have any questions.

**Comment by Endijs** [comment]
Something strange is happening. I still had problem. Tried to debug this. Edited source to log my private key and it turns out that its 128 bytes long, not 64 as it should be. And now when account gets created mnemonic phrase is just 12 words long, not 24 which i have as a backup from original setup. However now wallet and zilliqa js supports only 12 word phrase, not 24 word phrase. Do i have some strange legacy setup which had everything 2x longer or I managed to mess up something along the way when testing things before? I can scrap this account as those are just testnet zils, however its still interesting to know how i could have ended up in situation like this. If you have any idea, please let me know.
